# https://aider.chat/docs/llms/anthropic.html
- name: vertex_ai/claude-3-7-sonnet@20250219
  overeager: true
  edit_format: diff
  weak_model_name: vertex_ai/claude-3-5-sonnet-v2@20241022
  use_repo_map: true
  cache_control: true
  use_temperature: false
  examples_as_sys_msg: true
  extra_params:
    extra_headers:
      anthropic-beta: token-efficient-tools-2025-02-19,output-128k-2025-02-19
    max_tokens: 64000
    thinking:
      type: enabled
      budget_tokens: 32768
  editor_model_name: vertex_ai/claude-3-7-sonnet@20250219
  editor_edit_format: editor-diff
  accepts_settings:
    - thinking_tokens
